/**
 * Product Image Lists
 * AUTO-GENERATED FILE - Do not edit manually!
 * Generated by: scripts/generate-product-images.js
 * Last generated: 2026-06-14T12:46:14.598Z
 * 
 * Maps product folder names to their available images
 * This ensures reliable image loading for product detail pages
 * ALL images from each folder are automatically included here
 */

export const PRODUCT_IMAGES: Record<string, string[]> = {
  'art-tiles-page': [
    '/images/art-tiles-page/art-tiles-2.webp',
    '/images/art-tiles-page/art-tiles-3.webp',
    '/images/art-tiles-page/art-tiles-4.webp',
    '/images/art-tiles-page/art-tiles-adult-sample.webp',
    '/images/art-tiles-page/art-tiles-adult-sample2.webp',
    '/images/art-tiles-page/art-tiles-adults-collage-1.webp',
    '/images/art-tiles-page/art-tiles-adults-collage.webp',
    '/images/art-tiles-page/art-tiles-environment.webp',
    '/images/art-tiles-page/art-tiles-environmnet-2.webp',
    '/images/art-tiles-page/art-tiles-first.webp',
  ],

  'eco-bench-page': [
    '/images/eco-bench-page/Eco%20Bench-first.webp',
    '/images/eco-bench-page/eco-bench-collage-2.webp',
    '/images/eco-bench-page/eco-bench-collage.webp',
    '/images/eco-bench-page/eco-bench-environment-1.webp',
    '/images/eco-bench-page/eco-bench-environment-2.webp',
    '/images/eco-bench-page/eco-bench-environment-3.webp',
    '/images/eco-bench-page/eco-bench-environment.webp',
    '/images/eco-bench-page/eco-bench-single.webp',
  ],

  'eco-bricks-page': [
    '/images/eco-bricks-page/EcoBrick-collage.webp',
    '/images/eco-bricks-page/EcoBrick-environment2.webp',
    '/images/eco-bricks-page/EcoBrick.webp',
    '/images/eco-bricks-page/ecobrick-designs.webp',
    '/images/eco-bricks-page/ecobrick-environment.webp',
    '/images/eco-bricks-page/ecobrick-environment3.webp',
    '/images/eco-bricks-page/ecobrick-environment4.webp',
  ],

  'ECOBIKE-RACK-page': [
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK-collage.webp',
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK-environment.webp',
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK-environment2.webp',
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK.webp',
  ],

  'ECOBUSSTOP-page': [
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-collage.webp',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-collage2.webp',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-environment.webp',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-environment2.webp',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-first.webp',
  ],

  'Ecostreet-Furniture-page': [
    '/images/Ecostreet-Furniture-page/eco-furniture-collage.webp',
    '/images/Ecostreet-Furniture-page/eco-furniture-min.webp',
    '/images/Ecostreet-Furniture-page/eco-street-barrier.webp',
    '/images/Ecostreet-Furniture-page/eco-street-barrier2.webp',
    '/images/Ecostreet-Furniture-page/eco-street-barrier3.webp',
    '/images/Ecostreet-Furniture-page/eco-street-barrier4.webp',
    '/images/Ecostreet-Furniture-page/eco-street-collage.webp',
    '/images/Ecostreet-Furniture-page/eco-street-curb.webp',
    '/images/Ecostreet-Furniture-page/eco-street-curb2.webp',
    '/images/Ecostreet-Furniture-page/eco-street-environment.webp',
    '/images/Ecostreet-Furniture-page/eco-street-environment2.webp',
    '/images/Ecostreet-Furniture-page/eco-street-environment3.webp',
  ],

  'EPDM-free-Tiles-page': [
    '/images/EPDM-free-Tiles-page/EPDM-free-Tiles.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-2.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-collage.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-collage2.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-collage3.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-environment.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-environment2.webp',
    '/images/EPDM-free-Tiles-page/sbr-tile-environment3.webp',
  ],

  'epdm-tiles-page': [
    '/images/epdm-tiles-page/EPDM%20Rubber%20Ecotiles.webp',
    '/images/epdm-tiles-page/epdm-tile-4.webp',
    '/images/epdm-tiles-page/epdm-tile-environment-2.webp',
    '/images/epdm-tiles-page/epdm-tile-environment-3.webp',
    '/images/epdm-tiles-page/epdm-tile-environment-4.webp',
    '/images/epdm-tiles-page/epdm-tile-environment.webp',
    '/images/epdm-tiles-page/epdm-tiles-2.webp',
    '/images/epdm-tiles-page/epdm-tiles-collage.webp',
  ],

  'garden-planter-page': [
    '/images/garden-planter-page/Garden-Planter-collage.webp',
    '/images/garden-planter-page/Garden-Planter-collage2.webp',
    '/images/garden-planter-page/Garden-Planter-collage3.webp',
    '/images/garden-planter-page/Garden-Planter-environment.webp',
    '/images/garden-planter-page/Garden-Planter-environment2.webp',
    '/images/garden-planter-page/Garden-Planter.webp',
  ],

  'Waste-Bin-page': [
    '/images/Waste-Bin-page/waste-bin-collage.webp',
    '/images/Waste-Bin-page/waste-bin-environment.webp',
    '/images/Waste-Bin-page/waste-bin-environment2.webp',
    '/images/Waste-Bin-page/waste-bin-environment3.webp',
    '/images/Waste-Bin-page/waste-bin-environment4.webp',
    '/images/Waste-Bin-page/waste-bin-shop.webp',
  ],
};

/**
 * Get images for a product folder
 */
export function getProductImages(folderName: string): string[] {
  return PRODUCT_IMAGES[folderName] || [];
}
