/**
 * Product Image Lists
 * AUTO-GENERATED FILE - Do not edit manually!
 * Generated by: scripts/generate-product-images.js
 * Last generated: 2025-11-20T21:14:44.167Z
 * 
 * Maps product folder names to their available images
 * This ensures reliable image loading for product detail pages
 * ALL images from each folder are automatically included here
 */

export const PRODUCT_IMAGES: Record<string, string[]> = {
  'art-tiles-page': [
    '/images/art-tiles-page/art-tiles-2.jpg',
    '/images/art-tiles-page/art-tiles-3.jpg',
    '/images/art-tiles-page/art-tiles-4.jpg',
    '/images/art-tiles-page/art-tiles-adult-sample.jpg',
    '/images/art-tiles-page/art-tiles-adult-sample2.jpg',
    '/images/art-tiles-page/art-tiles-adults-collage-1.jpg',
    '/images/art-tiles-page/art-tiles-adults-collage.jpg',
    '/images/art-tiles-page/art-tiles-environment.jpg',
    '/images/art-tiles-page/art-tiles-environmnet-2.jpg',
    '/images/art-tiles-page/art-tiles-first.jpg',
  ],

  'eco-bench-page': [
    '/images/eco-bench-page/Eco%20Bench-first.jpg',
    '/images/eco-bench-page/eco-bench-collage-2.jpg',
    '/images/eco-bench-page/eco-bench-collage.jpg',
    '/images/eco-bench-page/eco-bench-environment-1.jpg',
    '/images/eco-bench-page/eco-bench-environment-2.jpg',
    '/images/eco-bench-page/eco-bench-environment-3.jpg',
    '/images/eco-bench-page/eco-bench-environment.jpg',
    '/images/eco-bench-page/eco-bench-single.jpg',
  ],

  'eco-bricks-page': [
    '/images/eco-bricks-page/EcoBrick-collage.jpg',
    '/images/eco-bricks-page/EcoBrick-environment2.jpg',
    '/images/eco-bricks-page/EcoBrick.jpg',
    '/images/eco-bricks-page/ecobrick-designs.jpg',
    '/images/eco-bricks-page/ecobrick-environment.jpg',
    '/images/eco-bricks-page/ecobrick-environment3.jpg',
    '/images/eco-bricks-page/ecobrick-environment4.jpg',
  ],

  'ECOBIKE-RACK-page': [
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK-collage.jpg',
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK-environment.jpg',
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK-environment2.jpg',
    '/images/ECOBIKE-RACK-page/ECOBIKE-RACK.jpg',
  ],

  'ECOBUSSTOP-page': [
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-collage.jpg',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-collage2.jpg',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-environment.jpg',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-environment2.jpg',
    '/images/ECOBUSSTOP-page/ECOBUSSTOP-first.jpg',
  ],

  'Ecostreet-Furniture-page': [
    '/images/Ecostreet-Furniture-page/eco-street-barrier.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-barrier2.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-barrier3.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-barrier4.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-collage.jpeg',
    '/images/Ecostreet-Furniture-page/eco-street-curb.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-curb2.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-environment.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-environment2.jpg',
    '/images/Ecostreet-Furniture-page/eco-street-environment3.jpg',
  ],

  'EPDM-free-Tiles-page': [
    '/images/EPDM-free-Tiles-page/EPDM-free-Tiles.jpg',
    '/images/EPDM-free-Tiles-page/sbr-tile-2.jpeg',
    '/images/EPDM-free-Tiles-page/sbr-tile-collage.jpg',
    '/images/EPDM-free-Tiles-page/sbr-tile-collage2.jpg',
    '/images/EPDM-free-Tiles-page/sbr-tile-collage3.jpg',
    '/images/EPDM-free-Tiles-page/sbr-tile-environment.jpg',
    '/images/EPDM-free-Tiles-page/sbr-tile-environment2.jpeg',
    '/images/EPDM-free-Tiles-page/sbr-tile-environment3.jpg',
  ],

  'epdm-tiles-page': [
    '/images/epdm-tiles-page/epdm-tile-4.jpg',
    '/images/epdm-tiles-page/EPDM-Tiles.jpg',
    '/images/epdm-tiles-page/epdm-tile-environment-2.jpeg',
    '/images/epdm-tiles-page/epdm-tile-environment-3.jpg',
    '/images/epdm-tiles-page/epdm-tile-environment-4.jpg',
    '/images/epdm-tiles-page/epdm-tile-environment.jpeg',
    '/images/epdm-tiles-page/epdm-tiles-2.jpg',
    '/images/epdm-tiles-page/epdm-tiles-collage.jpg',
  ],

  'garden-planter-page': [
    '/images/garden-planter-page/Garden-Planter-collage.jpg',
    '/images/garden-planter-page/Garden-Planter-collage2.jpg',
    '/images/garden-planter-page/Garden-Planter-collage3.jpg',
    '/images/garden-planter-page/Garden-Planter-environment.jpg',
    '/images/garden-planter-page/Garden-Planter-environment2.jpg',
    '/images/garden-planter-page/Garden-Planter.jpg',
  ],

  'Waste-Bin-page': [
    '/images/Waste-Bin-page/waste-bin-collage.jpeg',
    '/images/Waste-Bin-page/waste-bin-environment.jpeg',
    '/images/Waste-Bin-page/waste-bin-environment.jpg',
    '/images/Waste-Bin-page/waste-bin-environment2.jpg',
    '/images/Waste-Bin-page/waste-bin-environment3.jpg',
    '/images/Waste-Bin-page/waste-bin-shop.jpg',
  ],
};

/**
 * Get images for a product folder
 */
export function getProductImages(folderName: string): string[] {
  return PRODUCT_IMAGES[folderName] || [];
}
